spring:
  datasource:
    driver-className: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database_forum
    username: root
    password: root
    image: mysql
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true
jwt:
  secret: secret

