create table curso(
    id bigint generated by default as identity not null,
    nome varchar(50) not null,
    categoria varchar(50) not null,
    primary key(id)
);
insert into curso values
(1, 'Kotlin', 'Programação'),
(2, 'Python', 'Programação'),
(3, 'Excel Avançado', 'Administração')


