create table usuario(
     id bigint generated by default as identity not null UNIQUE,
     nome varchar(50) not null,
     email varchar(50) not null,
     password varchar(100) not null,
     primary key (id)
);
