create table usuario_role(
    id BIGINT generated by default as identity not null,
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    primary key(id),
    foreign key (usuario_id) references usuario(id),
    foreign key (role_id) references role(id)
);

